tags:
  - name: Categorias
    description: Endpoints de categorías
  - name: Productos
    description: Endpoints de productos
  - name: Ventas
    description: Endpoints de ventas
paths:
  # Endpoints de categorías
  /categories:
    get:
      tags:
        - Categorias
      summary: Encontrar todas las Categorías
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'

    post:
      tags:
        - Categorias
      summary: Agregar nueva Categoría
      parameters:
        - name: body
          in: body
          description: Información de la categoría
          required: true
          schema:
            $ref: '#/definitions/categories'
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'

  /categories/{id}:
    get:
      tags:
        - Categorias
      summary: Buscar por el id de la Categoría
      parameters:
        - name: id
          in: path
          description: Id de la Categoría
          required: true
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'

    put:
      tags:
        - Categorias
      summary: Actualizar la Categoría por el id
      parameters:
        - name: id
          in: path
          description: Id de la Categoría
          required: true
        - name: body
          in: body
          description: Información de la categoría
          required: true
          schema:
            $ref: '#/definitions/categories'
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'

    delete:
      tags:
        - Categorias
      summary: Eliminar la Categoría por el id
      parameters:
        - name: id
          in: path
          description: Id de la Categoría
          required: true
      responses:
        200:
          description: 'OK'
        404:
          description: 'Categoria no encontrada'
        500:
          description: 'Server Error'

   # Endpoints de productos
  /products:
    get:
      tags:
        - Productos
      summary: Encontrar todos los Productos
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'

    post:
      tags:
        - Productos
      summary: Agregar nuevo Producto
      parameters:
        - name: body
          in: body
          description: Información del producto
          required: true
          schema:
            $ref: '#/definitions/products'
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'

  /products/{id}:
    get:
      tags:
        - Productos
      summary: Buscar por el id del Producto
      parameters:
        - name: id
          in: path
          description: Id del Producto
          required: true
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'

    put:
      tags:
        - Productos
      summary: Actualizar el Producto por el id
      parameters:
        - name: id
          in: path
          description: Id del Producto
          required: true
        - name: body
          in: body
          description: Información del Producto
          required: true
          schema:
            $ref: '#/definitions/products'
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'

    delete:
      tags:
        - Productos
      summary: Eliminar el Producto por el id
      parameters:
        - name: id
          in: path
          description: Id del Producto
          required: true
      responses:
        200:
          description: 'OK'
        404:
          description: 'Producto no encontrado'
        500:
          description: 'Server Error'

  # Endpoints de ventas
  /sales:
    get:
      tags:
        - Ventas
      summary: Obtener todas las ventas
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'

    post:
      tags:
        - Ventas
      summary: Agregar nueva venta
      parameters:
        - name: body
          in: body
          description: Información de la venta
          required: true
          schema:
            $ref: '#/definitions/sales'
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'

  /sales/{id}:
    get:
      tags:
        - Ventas
      summary: Buscar venta por ID
      parameters:
        - name: id
          in: path
          description: ID de la venta
          required: true
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'

# definitions
definitions:
  categories:
    type: object
    required:
      - name
    properties:
      name:
        type: string
        description: Nombre de la categoría
      description:
        type: string
        description: Descripción de la categoría

  products:
    type: object
    required:
      - name
      - price
      - stock
      - category
    properties:
      name:
        type: string
        description: Nombre del producto
      description:
        type: string
        description: Descripción del producto
      price:
        type: number
        description: Precio del producto
      stock:
        type: number
        description: Stock disponible
      category:
        type: string
        description: Categoría del producto (id de la categoria)

  sales:
    type: object
    required:
      - date
      - client
      - products
      - totalAmount
    properties:
      date:
        type: string
        format: date
        description: Fecha de la venta
      client:
        type: string
        description: Cliente asociado a la venta
      products:
        type: array
        description: Productos vendidos con cantidades
        items:
          type: object
          properties:
            product:
              type: string
              description: ID del producto vendido
            quantity:
              type: number
              description: Cantidad vendida
